name: Angular CI/CD Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        working-directory: ./firebird-ng

      - name: Install Dependencies
        working-directory: ./firebird-ng
        run: npm install

      - name: Run Tests
        working-directory: ./firebird-ng
        run: npm run test:headless

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build
        working-directory: ./firebird-ng
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-site
          path: ./firebird-ng/dist/

  deploy:
    if: github.ref == 'refs/heads/master' || endsWith(github.ref, '-ci')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-site
          path: ./dist/firebird-ng

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/firebird-ng
